server:
  port: 38001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.cbs.entities                    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

spring:
  application:
    name: dept-provider                                       #暴露名不能更改
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    # 数据库名称
    url: jdbc:mysql://192.168.1.126:3306/cbs0001?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Ll427655..
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false # 表示不向注册中心注册
    fetch-registry: false # 由于注册中心的职责就是维护服务实例，所以它不需要去检索服务
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka17001.com:17001/eureka/,http://eureka17002.com:17002/eureka/,http://eureka17003.com:17003/eureka/
  instance:
    instance-id: dept-provider-hystrix-38001   #id
    prefer-ip-address: true     #访问路径可以显示IP地址
info: #yml后六一个空格，否则有可能读取不到
  app.name: dept-provider
  company.name: www.cbs.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$